<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>D:\Game\Steam\steamapps\common\RimWorld\Mods\血肉巢穴\1.6\Assemblies</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>D:\Game\Steam\steamapps\common\RimWorld\Mods\血肉巢穴\1.6\Assemblies</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HiveCreatureFramework">
      <HintPath>D:\Game\Steam\steamapps\common\RimWorld\Mods\巢群生物框架\1.6\Assemblies\net472\HiveCreatureFramework.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
